---

- name: 'Install Node.js 13'
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
    sudo apt-get install -y nodejs

- name: 'Use NVM to switch to Node js 13.8.0'
  shell: |
    sudo npm install -g n
    sudo n 13.8.0

- name: 'Install PM2'
  npm:
    name: pm2
    global: yes
